### ISSUE TITLE
Fix before release

### ISSUE THREAD

**Issue by TheWolfNL** [wvdeutekom/molliebot#1]
I'd suggest these changes:

**Remove `mol` from bot triggers.**
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L35
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L202

**Remove `fmt` print**
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L96
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L206
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L239

**Remove `log` print**
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L228

**Change to `mollie`**
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L212

**Handle empty array**
https://github.com/wvdeutekom/molliebot/blob/master/main.go#L236

**Comment by wvdeutekom** [comment]
Fixed in a0a1954519e9694249fa36451ec76bdd37ffbe2a 👍
